require('config.gitsigns')
require('config.lspconfig')
require('config.nvimtree')
require('config.snippy')
require('config.cmp')
require('config.toggleterm')
require('config.treesitter')
require('config.ui')
