" vim: nocp fen fdm=marker fdl=0 tw=78 cc=78 noet

" if &compatible
" 	set nocompatible
" endif

set exrc
set secure
set modeline
set noswapfile
set nobackup
set lazyredraw
set backspace=indent,eol,start
set mouse=nvi

" Key maps {{{
nnoremap ; :
"let mapleader = "\\"
let maplocalleader = "\<Space>"
map <LocalLeader>, :tabnew $MYVIMRC<cr>
" Don't use Ex mode, use Q for formatting:
map Q gq
" Make Y consistent with C and D.
nnoremap Y y$
" Copy whole file
nnoremap <Leader>y ggyG
" }}}


" Tabs {{{
set noexpandtab
set shiftround
set shiftwidth=4
set smarttab
set softtabstop=4
set tabstop=4
" }}}

" Indentation {{{
set autoindent
set copyindent
set preserveindent
set linebreak
" }}}


" Wildmenu {{{
set wildignore+=*.png,*.jpg,*.jpeg,*.gif
set wildignore+=__init__.py,*.pyc
set wildignore+=deps,_build,rel
" }}}

" Misc {{{
set fileformat=unix
set formatoptions-=cro
set iskeyword+=-
set shortmess=aIOt
set showtabline=1
set timeoutlen=500
set visualbell t_vb=
" }}}
