#!/usr/bin/env sh
# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaa65b2ff
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.75
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# window rules
# desktop 1
yabai -m rule --add app=Terminal space=1 manage=off
# desktop 2
yabai -m rule --add app=Code space=2
yabai -m rule --add app="^PSequel$" space=2
# desktop 3
yabai -m rule --add app="^Firefox Developer Edition$" space=3
yabai -m rule --add app="^Google Chrome$" space=3
yabai -m rule --add app="^Mail$" space=3
# desktop 4
yabai -m rule --add app=Spotify space=4
yabai -m rule --add app=YT\ Music space=4
# etc
yabai -m rule --add app="^VLC$" manage=off sticky=on
yabai -m rule --add app=Authy\ Desktop manage=off
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app=System\ Preferences manage=off sticky=on
yabai -m rule --add app=Telegram manage=off
yabai -m rule --add app=The\ Unarchiver manage=off

echo "yabai configuration loaded.."
