#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-kitty} # use your $TERMINAL with kitty as fallback
hc keybind $Mod-Shift-w spawn firefox-developer-edition

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Control-$key" use_index "$i"
        hc keybind "Control-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
    or , and . compare tags.focus.curframe_wcount = 2                   \
    . cycle_layout +1 vertical horizontal max vertical grid    \
    , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc set frame_border_normal_color '#906cff'
hc set frame_bg_normal_color '#906cff'
hc set frame_border_active_color '#cbe3e7'
hc set frame_bg_active_color '#1b182c'
hc set frame_border_width 2
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 4
hc set frame_gap 20
hc set window_gap 10
hc set frame_padding 10
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 2
hc set mouse_recenter_gap 0

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc attr theme.active.color '#1b182c'
hc attr theme.normal.color '#1b182c'
hc attr theme.urgent.color '#ffb378'
hc attr theme.inner_width 2
hc attr theme.inner_color black
hc attr theme.border_width 10
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 5
hc attr theme.floating.outer_color '#aaffe4'
hc attr theme.active.inner_color '#63f2f1'
hc attr theme.active.outer_color '#c991e1'
hc attr theme.background_color '#100e23'

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule instance='albert' focus=on pseudotile=on fullscreen=on

hc set tree_style '╾│ ├└╼─┐'

# essentials
hc spawn hsetroot -cover Pictures/astronaut-jellyfish-space-digital-art-uhdpaper.com-4K-107.jpg
hc spawn picom
hc spawn /usr/lib/at-spi-bus-launcher --launch-immediately
hc spawn /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
hc spawn /usr/bin/gnome-keyring-daemon --start --components=ssh
hc spawn /usr/bin/gnome-keyring-daemon --start --components=secrets
hc spawn /usr/bin/gnome-keyring-daemon --start --components=pkcs11

# unlock, just to be sure
hc unlock
# multi monitor setup
~/.config/herbstluftwm/monitors.sh
# autostart
hc spawn sh -c "GDK_BACKEND=x11 pamac-tray"
hc spawn blueman-applet
hc spawn nm-applet
hc spawn msm_notifier
hc spawn xfsettingsd
hc spawn light-locker
hc spawn albert
hc spawn telegram-desktop -autostart
# hc spawn start-pulseaudio-x11

# using Caps-Lock as Esc key
setxkbmap -option caps:swapescape

