#!/bin/bash
# vim: ft=bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

case "$XDG_SESSION_DESKTOP" in
    xfce )
        hc keybind $Mod-Shift-q spawn xfce4-session-logout
        ;;
    herbstluftwm )
        # Starts Gnome Polkit
        hc spawn /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
        hc keybind $Mod-Shift-q quit
        ;;
esac

hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return chain . \
	spawn "${TERMINAL:-kitty}" . \
	cycle_layout +1 grid

# basic movement
# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=({1..9} 0)
tag_keys=({1..9} 0)

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "Control-$key" use_index "$i"
        hc keybind "Control-Shift-$key" chain . \
			move_index "$i" . \
			use_index "$i" . \
			cycle_layout +1 grid
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-s set_attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space cycle_layout +1 grid max

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set focus_follows_mouse 1

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# THEME
THEME_BACKGROUND_COLOR="#0f111b"
THEME_ACTIVE_COLOR="#686f9a"
THEME_NORMAL_COLOR="#00a3cc"
THEME_URGENT_COLOR="#f2ce00"
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_active_color $THEME_BACKGROUND_COLOR
hc set frame_border_normal_color $THEME_NORMAL_COLOR
hc set frame_bg_normal_color $THEME_BACKGROUND_COLOR
hc set frame_bg_active_color $THEME_BACKGROUND_COLOR
hc set frame_border_width 2
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0

hc attr theme.active.color $THEME_ACTIVE_COLOR
hc attr theme.normal.color $THEME_BACKGROUND_COLOR
hc attr theme.urgent.color $THEME_URGENT_COLOR
hc attr theme.inner_width 0
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.active.inner_color $THEME_ACTIVE_COLOR
hc attr theme.normal.inner_color $THEME_NORMAL_COLOR
hc attr theme.urgent.inner_color $THEME_URGENT_COLOR
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width 0
hc attr theme.background_color $THEME_BACKGROUND_COLOR

hc set smart_window_surroundings off
hc set smart_frame_surroundings on

hc set window_gap 16
hc set frame_gap 8
hc set frame_padding 0

hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on focus=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' floating=on focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule instance='ulauncher' floating=on floatplacement=center
hc rule instance='xfce4-session-settings' floating=on floatplacement=center
hc rule instance='Thunar' floating=on floatplacement=center
hc rule instance='vlc' floating=on focus=on
hc rule instance='galculator' floating=on focus=on

hc set tree_style '╾│ ├└╼─┐'

# autostart
hc spawn picom -b -C #--dbus
hc spawn ulauncher --hide-window
hc spawn hsetroot -solid $THEME_BACKGROUND_COLOR
#hc spawn xmodmap ~/.Xmodmap

# shortcut keys to launch stuff
[ -f $HOME/.config/herbstluftwm/shortcuts.sh ] && . $HOME/.config/herbstluftwm/shortcuts.sh

# multi monitor setup
[ -f $HOME/.config/herbstluftwm/monitors.sh ] && . $HOME/.config/herbstluftwm/monitors.sh

# local config
[ -f $HOME/.herbstluftwm_local.sh ] && . $HOME/.herbstluftwm_local.sh
