# vim ft=sh
if [[ -f "/usr/share/git/completion/git-completion.bash" ]]; then
	. /usr/share/git/completion/git-completion.bash
fi

alias g="git"
__git_complete g __git_main

alias h="history"
alias j="jobs -l"
alias ls="ls -h --color=always"
alias mkdir="mkdir -pv"
alias tmux-trigger="tmux attach -d -t $USER || tmux new-session -s $USER"
alias tmux="tmux -2 -u"
alias vi="vim --clean"
alias wget="wget -c"
